# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Registeration.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(981, 617)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background_image_label = QtWidgets.QLabel(self.centralwidget)
        self.background_image_label.setGeometry(QtCore.QRect(4, -5, 971, 591))
        self.background_image_label.setStyleSheet("\n"
"background-image: url(:/registeration/without_date.png);")
        self.background_image_label.setText("")
        self.background_image_label.setObjectName("background_image_label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(230, 110, 311, 401))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Name_label = QtWidgets.QLabel(self.widget)
        self.Name_label.setStyleSheet("color:rgb(44,88,145);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.Name_label.setObjectName("Name_label")
        self.verticalLayout.addWidget(self.Name_label)
        self.Name_lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.Name_lineEdit_2.setStyleSheet("border-radius:15px;\n"
"  padding: 10px;\n"
"\n"
"border-style:outset;\n"
"border-width:1px;\n"
"border-color:black;")
        self.Name_lineEdit_2.setObjectName("Name_lineEdit_2")
        self.verticalLayout.addWidget(self.Name_lineEdit_2)
        self.sex_label = QtWidgets.QLabel(self.widget)
        self.sex_label.setStyleSheet("color:rgb(44,88,145);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.sex_label.setObjectName("sex_label")
        self.verticalLayout.addWidget(self.sex_label)
        self.Name_lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.Name_lineEdit_3.setStyleSheet("border-radius:15px;\n"
"  padding: 10px;\n"
"\n"
"border-style:outset;\n"
"border-width:1px;\n"
"border-color:black;")
        self.Name_lineEdit_3.setObjectName("Name_lineEdit_3")
        self.verticalLayout.addWidget(self.Name_lineEdit_3)
        self.diagnosis_label = QtWidgets.QLabel(self.widget)
        self.diagnosis_label.setStyleSheet("color:rgb(44,88,145);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.diagnosis_label.setObjectName("diagnosis_label")
        self.verticalLayout.addWidget(self.diagnosis_label)
        self.Name_lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        self.Name_lineEdit_5.setStyleSheet("border-radius:15px;\n"
"  padding: 10px;\n"
"\n"
"border-style:outset;\n"
"border-width:1px;\n"
"border-color:black;")
        self.Name_lineEdit_5.setObjectName("Name_lineEdit_5")
        self.verticalLayout.addWidget(self.Name_lineEdit_5)
        self.other_discreption_label = QtWidgets.QLabel(self.widget)
        self.other_discreption_label.setStyleSheet("color:rgb(44,88,145);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.other_discreption_label.setObjectName("other_discreption_label")
        self.verticalLayout.addWidget(self.other_discreption_label)
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        self.textEdit.setStyleSheet("border-radius:15px;\n"
"  padding: 4px;\n"
"\n"
"border-style:outset;\n"
"border-width:1px;\n"
"border-color:black;")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(580, 110, 291, 261))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.age_label = QtWidgets.QLabel(self.widget1)
        self.age_label.setStyleSheet("color:rgb(44,88,145);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.age_label.setObjectName("age_label")
        self.verticalLayout_2.addWidget(self.age_label)
        self.Name_lineEdit_7 = QtWidgets.QLineEdit(self.widget1)
        self.Name_lineEdit_7.setStyleSheet("border-radius:15px;\n"
"  padding: 10px;\n"
"\n"
"border-style:outset;\n"
"border-width:1px;\n"
"border-color:black;")
        self.Name_lineEdit_7.setObjectName("Name_lineEdit_7")
        self.verticalLayout_2.addWidget(self.Name_lineEdit_7)
        self.procedure_label = QtWidgets.QLabel(self.widget1)
        self.procedure_label.setStyleSheet("color:rgb(44,88,145);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.procedure_label.setObjectName("procedure_label")
        self.verticalLayout_2.addWidget(self.procedure_label)
        self.Name_lineEdit_4 = QtWidgets.QLineEdit(self.widget1)
        self.Name_lineEdit_4.setStyleSheet("border-radius:15px;\n"
"  padding: 10px;\n"
"\n"
"border-style:outset;\n"
"border-width:1px;\n"
"border-color:black;")
        self.Name_lineEdit_4.setObjectName("Name_lineEdit_4")
        self.verticalLayout_2.addWidget(self.Name_lineEdit_4)
        self.diagnosis_profesional_label = QtWidgets.QLabel(self.widget1)
        self.diagnosis_profesional_label.setStyleSheet("color:rgb(44,88,145);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.diagnosis_profesional_label.setObjectName("diagnosis_profesional_label")
        self.verticalLayout_2.addWidget(self.diagnosis_profesional_label)
        self.Name_lineEdit_6 = QtWidgets.QLineEdit(self.widget1)
        self.Name_lineEdit_6.setStyleSheet("border-radius:15px;\n"
"  padding: 10px;\n"
"\n"
"border-style:outset;\n"
"border-width:1px;\n"
"border-color:black;")
        self.Name_lineEdit_6.setObjectName("Name_lineEdit_6")
        self.verticalLayout_2.addWidget(self.Name_lineEdit_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.preview_pushButton = QtWidgets.QPushButton(self.widget1)
        self.preview_pushButton.setStyleSheet("background-color: rgb(16,130,219);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255,255,255);\n"
"\n"
"border-radius:15px;\n"
"  padding: 10px;\n"
"\n"
"")
        self.preview_pushButton.setObjectName("preview_pushButton")
        self.horizontalLayout.addWidget(self.preview_pushButton)
        self.save_pushButton = QtWidgets.QPushButton(self.widget1)
        self.save_pushButton.setStyleSheet("background-color: rgb(16,130,219);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255,255,255);\n"
"\n"
"border-radius:15px;\n"
"  padding: 10px;\n"
"\n"
"")
        self.save_pushButton.setObjectName("save_pushButton")
        self.horizontalLayout.addWidget(self.save_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(50, 70, 31, 111))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.home_label = QtWidgets.QLabel(self.widget2)
        self.home_label.setText("")
        self.home_label.setObjectName("home_label")
        self.verticalLayout_3.addWidget(self.home_label)
        self.setting_label = QtWidgets.QLabel(self.widget2)
        self.setting_label.setText("")
        self.setting_label.setObjectName("setting_label")
        self.verticalLayout_3.addWidget(self.setting_label)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 981, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Name_label.setText(_translate("MainWindow", "Name"))
        self.sex_label.setText(_translate("MainWindow", "Sex"))
        self.diagnosis_label.setText(_translate("MainWindow", "Diagnosis"))
        self.other_discreption_label.setText(_translate("MainWindow", "Other discription"))
        self.age_label.setText(_translate("MainWindow", "Age"))
        self.procedure_label.setText(_translate("MainWindow", "Procedure"))
        self.diagnosis_profesional_label.setText(_translate("MainWindow", "Diagnosing Profesional"))
        self.preview_pushButton.setText(_translate("MainWindow", "Preview"))
        self.save_pushButton.setText(_translate("MainWindow", "Save"))
import this_is_resource_rc
