# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Search.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Search_w(object):
    def setupUi(self, Search_w):
        Search_w.setObjectName("Search_w")
        Search_w.setEnabled(True)
        Search_w.resize(1113, 598)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Search_w.sizePolicy().hasHeightForWidth())
        Search_w.setSizePolicy(sizePolicy)
        Search_w.setStyleSheet("")
        self.Background_image_lable = QtWidgets.QLabel(Search_w)
        self.Background_image_lable.setGeometry(QtCore.QRect(0, -10, 1101, 601))
        self.Background_image_lable.setStyleSheet("background-image: url(:/Search/without_date.png);\n"
"")
        self.Background_image_lable.setText("")
        self.Background_image_lable.setObjectName("Background_image_lable")
        self.exit_label = QtWidgets.QLabel(Search_w)
        self.exit_label.setGeometry(QtCore.QRect(20, 480, 71, 71))
        self.exit_label.setStyleSheet("\n"
"background-image: url(:/newPrefix/Screenshot 2024-10-04 174855.png);")
        self.exit_label.setText("")
        self.exit_label.setObjectName("exit_label")
        self.listWidget = QtWidgets.QListWidget(Search_w)
        self.listWidget.setGeometry(QtCore.QRect(150, 260, 811, 311))
        self.listWidget.setObjectName("listWidget")
        self.Heading_bar_label = QtWidgets.QLabel(Search_w)
        self.Heading_bar_label.setGeometry(QtCore.QRect(150, 220, 811, 40))
        self.Heading_bar_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Heading_bar_label.setAutoFillBackground(False)
        self.Heading_bar_label.setStyleSheet("background-color: rgb(16,130,219);\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"color:rgb(255,255,255);\n"
"\n"
"border-style:outset;\n"
"border-width:1px;\n"
"border-color:black;\n"
"\n"
"")
        self.Heading_bar_label.setObjectName("Heading_bar_label")
        self.play_lable = QtWidgets.QLabel(Search_w)
        self.play_lable.setGeometry(QtCore.QRect(30, 250, 51, 51))
        self.play_lable.setText("")
        self.play_lable.setObjectName("play_lable")
        self.widget = QtWidgets.QWidget(Search_w)
        self.widget.setGeometry(QtCore.QRect(150, 110, 611, 91))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Date_label = QtWidgets.QLabel(self.widget)
        self.Date_label.setMaximumSize(QtCore.QSize(150, 16777215))
        self.Date_label.setStyleSheet("color:rgb(44,88,145);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.Date_label.setObjectName("Date_label")
        self.horizontalLayout_2.addWidget(self.Date_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.Name_label = QtWidgets.QLabel(self.widget)
        self.Name_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.Name_label.setStyleSheet("color:rgb(44,88,145);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.Name_label.setObjectName("Name_label")
        self.horizontalLayout_2.addWidget(self.Name_label)
        spacerItem1 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dateEdit = QtWidgets.QDateEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit.sizePolicy().hasHeightForWidth())
        self.dateEdit.setSizePolicy(sizePolicy)
        self.dateEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.dateEdit.setStyleSheet("border-radius:10px;\n"
"  padding: 5px;\n"
"\n"
"border-style:outset;\n"
"border-width:1px;\n"
"border-color:black;")
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout.addWidget(self.dateEdit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.Name_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.Name_lineEdit.setStyleSheet("border-radius:15px;\n"
"  padding: 10px;\n"
"\n"
"border-style:outset;\n"
"border-width:1px;\n"
"border-color:black;")
        self.Name_lineEdit.setObjectName("Name_lineEdit")
        self.horizontalLayout.addWidget(self.Name_lineEdit)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.Search_pushButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Search_pushButton.sizePolicy().hasHeightForWidth())
        self.Search_pushButton.setSizePolicy(sizePolicy)
        self.Search_pushButton.setMinimumSize(QtCore.QSize(150, 0))
        self.Search_pushButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.Search_pushButton.setStyleSheet("background-color: rgb(16,130,219);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255,255,255);\n"
"\n"
"border-radius:15px;\n"
"  padding: 10px;\n"
"\n"
"")
        self.Search_pushButton.setObjectName("Search_pushButton")
        self.horizontalLayout.addWidget(self.Search_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.widget1 = QtWidgets.QWidget(Search_w)
        self.widget1.setGeometry(QtCore.QRect(30, 60, 51, 131))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Home_lable = QtWidgets.QLabel(self.widget1)
        self.Home_lable.setText("")
        self.Home_lable.setObjectName("Home_lable")
        self.verticalLayout_2.addWidget(self.Home_lable)
        spacerItem4 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem4)
        self.Setting_lable = QtWidgets.QLabel(self.widget1)
        self.Setting_lable.setText("")
        self.Setting_lable.setObjectName("Setting_lable")
        self.verticalLayout_2.addWidget(self.Setting_lable)
        self.Background_image_lable.raise_()
        self.Search_pushButton.raise_()
        self.exit_label.raise_()
        self.Date_label.raise_()
        self.Name_label.raise_()
        self.Name_lineEdit.raise_()
        self.dateEdit.raise_()
        self.listWidget.raise_()
        self.Heading_bar_label.raise_()
        self.Home_lable.raise_()
        self.Setting_lable.raise_()
        self.play_lable.raise_()

        self.retranslateUi(Search_w)
        QtCore.QMetaObject.connectSlotsByName(Search_w)

    def retranslateUi(self, Search_w):
        _translate = QtCore.QCoreApplication.translate
        Search_w.setWindowTitle(_translate("Search_w", "Form"))
        self.Heading_bar_label.setText(_translate("Search_w", "   Name                 Age-Sex           Profesional          Diagnosis            Time          Procedure"))
        self.Date_label.setText(_translate("Search_w", "Date"))
        self.Name_label.setText(_translate("Search_w", "Name"))
        self.Search_pushButton.setText(_translate("Search_w", "Search"))
import this_is_resource_rc
