# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'third.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1064, 666)
        MainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backgroundimg_label = QtWidgets.QLabel(self.centralwidget)
        self.backgroundimg_label.setGeometry(QtCore.QRect(0, -10, 1071, 661))
        self.backgroundimg_label.setStyleSheet("\n"
"background-image: url(:/Login/login_back.png);")
        self.backgroundimg_label.setText("")
        self.backgroundimg_label.setObjectName("backgroundimg_label")
        self.Logo_label = QtWidgets.QLabel(self.centralwidget)
        self.Logo_label.setGeometry(QtCore.QRect(410, 50, 191, 211))
        self.Logo_label.setStyleSheet("background-image: url(:/newPrefix/logo.png);")
        self.Logo_label.setText("")
        self.Logo_label.setObjectName("Logo_label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(350, 270, 351, 312))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Stayfit_label = QtWidgets.QLabel(self.widget)
        self.Stayfit_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Stayfit_label.setAutoFillBackground(False)
        self.Stayfit_label.setStyleSheet("font: 34pt \"Myanmar Text\";\n"
"\n"
"\n"
"font-weight:500;\n"
"color: rgb(16,130,219);\n"
"\n"
"")
        self.Stayfit_label.setObjectName("Stayfit_label")
        self.verticalLayout_2.addWidget(self.Stayfit_label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Name_label = QtWidgets.QLabel(self.widget)
        self.Name_label.setStyleSheet("font: 12pt \"Myanmar Text\";\n"
"\n"
"\n"
"font-weight:500;\n"
"color: rgb(16,130,219);\n"
"")
        self.Name_label.setObjectName("Name_label")
        self.verticalLayout.addWidget(self.Name_label)
        self.Name_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.Name_lineEdit.setStyleSheet("border-radius:10px;\n"
"  padding: 10px;\n"
"\n"
"border-style:outset;\n"
"border-width:1px;\n"
"border-color:black;")
        self.Name_lineEdit.setObjectName("Name_lineEdit")
        self.verticalLayout.addWidget(self.Name_lineEdit)
        self.Passward_label = QtWidgets.QLabel(self.widget)
        self.Passward_label.setStyleSheet("font: 12pt \"Myanmar Text\";\n"
"\n"
"\n"
"font-weight:500;\n"
"color: rgb(16,130,219);\n"
"")
        self.Passward_label.setObjectName("Passward_label")
        self.verticalLayout.addWidget(self.Passward_label)
        self.Passward_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.Passward_lineEdit.setStyleSheet("border-radius:10px;\n"
"  padding: 10px;\n"
"\n"
"border-style:outset;\n"
"border-width:1px;\n"
"border-color:black;")
        self.Passward_lineEdit.setObjectName("Passward_lineEdit")
        self.verticalLayout.addWidget(self.Passward_lineEdit)
        self.Enter_pushButton = QtWidgets.QPushButton(self.widget)
        self.Enter_pushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Enter_pushButton.sizePolicy().hasHeightForWidth())
        self.Enter_pushButton.setSizePolicy(sizePolicy)
        self.Enter_pushButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.Enter_pushButton.setStyleSheet("background-color: rgb(16,130,219);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255,255,255);\n"
"\n"
"border-radius:15px;\n"
"  padding: 10px;\n"
"\n"
"")
        self.Enter_pushButton.setObjectName("Enter_pushButton")
        self.verticalLayout.addWidget(self.Enter_pushButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1064, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Name_lineEdit, self.Passward_lineEdit)
        MainWindow.setTabOrder(self.Passward_lineEdit, self.Enter_pushButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Stayfit_label.setText(_translate("MainWindow", "        Stayfit"))
        self.Name_label.setText(_translate("MainWindow", "Name"))
        self.Passward_label.setText(_translate("MainWindow", "Passward"))
        self.Enter_pushButton.setText(_translate("MainWindow", "Enter"))
import this_is_resource_rc
