# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Registeration.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(982, 609)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background_image_label = QtWidgets.QLabel(self.centralwidget)
        self.background_image_label.setGeometry(QtCore.QRect(4, -5, 971, 591))
        self.background_image_label.setStyleSheet("background-image: url(:/newPrefix/without_date.png);")
        self.background_image_label.setText("")
        self.background_image_label.setObjectName("background_image_label")
        self.setting_label = QtWidgets.QLabel(self.centralwidget)
        self.setting_label.setGeometry(QtCore.QRect(50, 150, 31, 41))
        self.setting_label.setText("")
        self.setting_label.setObjectName("setting_label")
        self.home_label = QtWidgets.QLabel(self.centralwidget)
        self.home_label.setGeometry(QtCore.QRect(50, 60, 31, 41))
        self.home_label.setText("")
        self.home_label.setObjectName("home_label")
        self.Name_label = QtWidgets.QLabel(self.centralwidget)
        self.Name_label.setGeometry(QtCore.QRect(240, 110, 71, 41))
        self.Name_label.setStyleSheet("color:rgb(44,88,145);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.Name_label.setObjectName("Name_label")
        self.save_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.save_pushButton.setGeometry(QtCore.QRect(750, 470, 111, 41))
        self.save_pushButton.setStyleSheet("background-color: rgb(16,130,219);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255,255,255);\n"
"\n"
"border-radius:15px;\n"
"  padding: 10px;\n"
"\n"
"")
        self.save_pushButton.setObjectName("save_pushButton")
        self.preview_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.preview_pushButton.setGeometry(QtCore.QRect(590, 470, 111, 41))
        self.preview_pushButton.setStyleSheet("background-color: rgb(16,130,219);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255,255,255);\n"
"\n"
"border-radius:15px;\n"
"  padding: 10px;\n"
"\n"
"")
        self.preview_pushButton.setObjectName("preview_pushButton")
        self.Name_lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.Name_lineEdit_3.setGeometry(QtCore.QRect(230, 230, 291, 41))
        self.Name_lineEdit_3.setStyleSheet("border-radius:15px;\n"
"  padding: 10px;\n"
"\n"
"border-style:outset;\n"
"border-width:1px;\n"
"border-color:black;")
        self.Name_lineEdit_3.setObjectName("Name_lineEdit_3")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(230, 390, 301, 121))
        self.textEdit.setStyleSheet("border-radius:15px;\n"
"  padding: 4px;\n"
"\n"
"border-style:outset;\n"
"border-width:1px;\n"
"border-color:black;")
        self.textEdit.setObjectName("textEdit")
        self.sex_label = QtWidgets.QLabel(self.centralwidget)
        self.sex_label.setGeometry(QtCore.QRect(240, 200, 32, 24))
        self.sex_label.setStyleSheet("color:rgb(44,88,145);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.sex_label.setObjectName("sex_label")
        self.diagnosis_label = QtWidgets.QLabel(self.centralwidget)
        self.diagnosis_label.setGeometry(QtCore.QRect(240, 280, 86, 24))
        self.diagnosis_label.setStyleSheet("color:rgb(44,88,145);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.diagnosis_label.setObjectName("diagnosis_label")
        self.diagnosis_profesional_label = QtWidgets.QLabel(self.centralwidget)
        self.diagnosis_profesional_label.setGeometry(QtCore.QRect(590, 280, 211, 28))
        self.diagnosis_profesional_label.setStyleSheet("color:rgb(44,88,145);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.diagnosis_profesional_label.setObjectName("diagnosis_profesional_label")
        self.other_discreption_label = QtWidgets.QLabel(self.centralwidget)
        self.other_discreption_label.setGeometry(QtCore.QRect(240, 360, 151, 24))
        self.other_discreption_label.setStyleSheet("color:rgb(44,88,145);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.other_discreption_label.setObjectName("other_discreption_label")
        self.procedure_label = QtWidgets.QLabel(self.centralwidget)
        self.procedure_label.setGeometry(QtCore.QRect(590, 190, 89, 41))
        self.procedure_label.setStyleSheet("color:rgb(44,88,145);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.procedure_label.setObjectName("procedure_label")
        self.Name_lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.Name_lineEdit_2.setGeometry(QtCore.QRect(230, 150, 291, 40))
        self.Name_lineEdit_2.setStyleSheet("border-radius:15px;\n"
"  padding: 10px;\n"
"\n"
"border-style:outset;\n"
"border-width:1px;\n"
"border-color:black;")
        self.Name_lineEdit_2.setObjectName("Name_lineEdit_2")
        self.Name_lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.Name_lineEdit_5.setGeometry(QtCore.QRect(230, 310, 291, 40))
        self.Name_lineEdit_5.setStyleSheet("border-radius:15px;\n"
"  padding: 10px;\n"
"\n"
"border-style:outset;\n"
"border-width:1px;\n"
"border-color:black;")
        self.Name_lineEdit_5.setObjectName("Name_lineEdit_5")
        self.age_label = QtWidgets.QLabel(self.centralwidget)
        self.age_label.setGeometry(QtCore.QRect(590, 110, 34, 42))
        self.age_label.setStyleSheet("color:rgb(44,88,145);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.age_label.setObjectName("age_label")
        self.Name_lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.Name_lineEdit_6.setGeometry(QtCore.QRect(580, 310, 291, 41))
        self.Name_lineEdit_6.setStyleSheet("border-radius:15px;\n"
"  padding: 10px;\n"
"\n"
"border-style:outset;\n"
"border-width:1px;\n"
"border-color:black;")
        self.Name_lineEdit_6.setObjectName("Name_lineEdit_6")
        self.Name_lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.Name_lineEdit_4.setGeometry(QtCore.QRect(580, 230, 291, 41))
        self.Name_lineEdit_4.setStyleSheet("border-radius:15px;\n"
"  padding: 10px;\n"
"\n"
"border-style:outset;\n"
"border-width:1px;\n"
"border-color:black;")
        self.Name_lineEdit_4.setObjectName("Name_lineEdit_4")
        self.Name_lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.Name_lineEdit_7.setGeometry(QtCore.QRect(580, 150, 291, 41))
        self.Name_lineEdit_7.setStyleSheet("border-radius:15px;\n"
"  padding: 10px;\n"
"\n"
"border-style:outset;\n"
"border-width:1px;\n"
"border-color:black;")
        self.Name_lineEdit_7.setObjectName("Name_lineEdit_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 982, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Name_label.setText(_translate("MainWindow", "Name"))
        self.save_pushButton.setText(_translate("MainWindow", "Save"))
        self.preview_pushButton.setText(_translate("MainWindow", "Preview"))
        self.sex_label.setText(_translate("MainWindow", "Sex"))
        self.diagnosis_label.setText(_translate("MainWindow", "Diagnosis"))
        self.diagnosis_profesional_label.setText(_translate("MainWindow", "Diagnosing Profesional"))
        self.other_discreption_label.setText(_translate("MainWindow", "Other discription"))
        self.procedure_label.setText(_translate("MainWindow", "Procedure"))
        self.age_label.setText(_translate("MainWindow", "Age"))
import this_is_resource_rc
