# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'third.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1064, 666)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -10, 1071, 661))
        self.label.setStyleSheet("background-image: url(:/newPrefix/login_back.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(410, 50, 191, 211))
        self.label_2.setStyleSheet("background-image: url(:/newPrefix/logo.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(430, 270, 171, 71))
        self.label_3.setStyleSheet("font: 34pt \"Myanmar Text\";\n"
"\n"
"\n"
"font-weight:500;\n"
"color: rgb(16,130,219);\n"
"\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(350, 330, 81, 31))
        self.label_4.setStyleSheet("font: 12pt \"Myanmar Text\";\n"
"\n"
"\n"
"font-weight:500;\n"
"color: rgb(16,130,219);\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(350, 420, 91, 31))
        self.label_5.setStyleSheet("font: 12pt \"Myanmar Text\";\n"
"\n"
"\n"
"font-weight:500;\n"
"color: rgb(16,130,219);\n"
"")
        self.label_5.setObjectName("label_5")
        self.Name_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Name_lineEdit.setGeometry(QtCore.QRect(350, 370, 321, 41))
        self.Name_lineEdit.setStyleSheet("border-radius:10px;\n"
"  padding: 10px;\n"
"\n"
"border-style:outset;\n"
"border-width:1px;\n"
"border-color:black;")
        self.Name_lineEdit.setObjectName("Name_lineEdit")
        self.Name_lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.Name_lineEdit_2.setGeometry(QtCore.QRect(350, 450, 321, 41))
        self.Name_lineEdit_2.setStyleSheet("border-radius:10px;\n"
"  padding: 10px;\n"
"\n"
"border-style:outset;\n"
"border-width:1px;\n"
"border-color:black;")
        self.Name_lineEdit_2.setObjectName("Name_lineEdit_2")
        self.Search_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Search_pushButton.setGeometry(QtCore.QRect(540, 510, 131, 41))
        self.Search_pushButton.setStyleSheet("background-color: rgb(16,130,219);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255,255,255);\n"
"\n"
"border-radius:15px;\n"
"  padding: 10px;\n"
"\n"
"")
        self.Search_pushButton.setObjectName("Search_pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1064, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Stayfit"))
        self.label_4.setText(_translate("MainWindow", "Name"))
        self.label_5.setText(_translate("MainWindow", "Passward"))
        self.Search_pushButton.setText(_translate("MainWindow", "Enter"))
import this_is_resource_rc
